name: Check for stale issues and PRs

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v4.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "Marked as stale due to inactivity. Will close in 7 days."
          stale-pr-message: "Marked as stale due to inactivity. Will close in 7 days."
          close-issue-message: "Closed due to inactivity."
          close-pr-message: "Closed due to inactivity."
          stale-issue-label: "Stale"
          stale-pr-label: "Stale"
